name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Get Docker Desktop IP
        id: get_ip
        run: echo "::set-output name=ip::$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}' | cut -d'/' -f3 | cut -d':' -f1)"

      - name: Set up Kubernetes with Docker Desktop IP
        run: |
          kubectl config set-cluster docker-desktop --server=https://${{ steps.get_ip.outputs.ip }} --insecure-skip-tls-verify
          kubectl config set-context docker-desktop --cluster=docker-desktop
          kubectl config use-context docker-desktop

      - name: Build and Push Docker Images
        run: |
          docker login --username razyal --password ${{ secrets.DOCKER_TOKEN }}
          docker build . -t razyal/twitter_insight:latest
          docker push razyal/twitter_insight:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/counter-incrementer-deployment.yaml --username razyal --password ${{ secrets.DOCKER_TOKEN }} --validate=false
          kubectl apply -f kubernetes/counter-incrementer-service.yaml --username razyal --password ${{ secrets.DOCKER_TOKEN }} --validate=false

      - name: Check status
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get services
