name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        run: |
          sudo apt-get update -q
          sudo apt-get install -y kubectl

      - uses: actions/checkout@v3
      - name: Build and Push Docker Images
        run: |
          docker login --username razyal8 --password ${{ secrets.TOKEN }} ghcr.io
          docker build . --tag ghcr.io/razyal8/twitter_insight:latest
          docker push ghcr.io/razyal8/twitter_insight:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/counter-incrementer-deployment.yaml
          kubectl apply -f kubernetes/counter-incrementer-service.yaml
