name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Start kubectl proxy
        run: kubectl proxy --port=6443 &

      - name: Wait for kubectl proxy to start
        run: sleep 30

      - name: Authenticate with Kubernetes cluster
        run: kubectl config set-cluster docker-desktop --server=http://localhost:6443 --insecure-skip-tls-verify

      - name: Set context to docker-desktop
        run: |
          kubectl config set-context docker-desktop --cluster=docker-desktop
          kubectl config use-context docker-desktop

      - name: Build and Push Docker Images
        run: |
          docker login --username razyal --password ${{ secrets.DOCKER_TOKEN }}
          docker build . -t razyal/twitter_insight:latest
          docker push razyal/twitter_insight:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/counter-incrementer-deployment.yaml --validate=false
          kubectl apply -f kubernetes/counter-incrementer-service.yaml --validate=false

      - name: Check status
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get services
