name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Expose Docker Desktop Kubernetes API
        run: kubectl proxy --port=6443 &

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Kubernetes Configuration
        run: |
          mkdir -p $HOME/.kube
          kubectl config set-cluster docker-desktop --server=http://localhost:6443
          kubectl config set-context docker-desktop --cluster=docker-desktop
          kubectl config use-context docker-desktop

      - name: Check Kubernetes Configuration
        run: kubectl config view

      - name: Check Kubernetes API Server
        run: kubectl cluster-info

      - name: Deploy to Kubernetes
        run: kubectl apply -f kubernetes/counter-incrementer-deployment.yaml --validate=false
