name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Build and Push Docker Images
        run: |
          docker login --username razyal --password ${{ secrets.DOCKER_TOKEN }}
          docker build . -t razyal/twitter_insight:latest
          docker push razyal/twitter_insight:latest

      - name: Kubernets
        run: |
          kubectl config get-contexts
          kubectl config use-context docker-desktop

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/counter-incrementer-deployment.yaml --validate=false
          kubectl apply -f kubernetes/counter-incrementer-service.yaml --validate=false

      - name: Check status
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get services
