name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      GITHUB_CONTAINER_REGISTRY: ${{ secrets.GITHUB_CONTAINER_REGISTRY }}

    steps:
      - name: prints
        run: |
          echo "Built Docker images:"
          echo "token: ${{ secrets.GITHUB_TOKEN }}"
          echo secrets.GITHUB_TOKEN

      - uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          sudo apt-get update -q
          sudo apt-get install -y kubectl

      - name: Build and Push Docker Images
        run: |
          docker login --username razyal8 --password-stdin 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
          docker build . --tag ghcr.io/razyal8/twitter_insight:latest
          docker push ghcr.io/razyal8/twitter_insight:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f Kubernetes/counter-incrementer/counter-incrementer-deployment.yaml
          kubectl apply -f Kubernetes/counter-incrementer/counter-incrementer-service.yaml
          kubectl apply -f Kubernetes/counter-printer/counter-printer-deployment.yaml
          kubectl apply -f Kubernetes/counter-printer/counter-printer-service.yaml
