name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Docker Images
        run: |
          docker login --username razyal8 --password ${{ secrets.TOKEN }} ghcr.io
          docker build . --tag ghcr.io/razyal8/twitter_insight:latest
          docker push ghcr.io/razyal8/twitter_insight:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/counter-incrementer-deployment.yaml --validate=false
          kubectl apply -f kubernetes/counter-incrementer-service.yaml --validate=false

      - name: Check status
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get services
